## YAML Override template
## original/file.tpl: override/file.tpl
---
system/SearchModule/Resources/views/Block/search.tpl: themes/Andreas08Theme/Resources/views/modules/Search/Block/search.tpl
system/BlocksModule/Resources/views/Block/extmenu_topnav.tpl: themes/Andreas08Theme/Resources/views/modules/Blocks/Block/extmenu_topnav.tpl